---
hostname: s1-c9k-sw1
platform_role: access_switch
site: site1
platform_type: iosxe

archive_path: flash:archive

# Management
mgmt_interface: GigabitEthernet0/0
mgmt_description: OoB_Mgmt
mgmt_vrf: Mgmt-vrf
mgmt_ip: 10.82.9.129/28
mgmt_gw: 10.82.9.142

# VTP
vtp_mode: transparent

spanning_tree:
  vlan_priority: 4096

# License
license_level: network-advantage
license_addon: dna-advantage

# Uplinks - abstracted as logical links
uplinks:
  - name: Port-channel1
    description: LAG_TO_S1-NCS540
    type: port_channel
    mode: trunk
    native_vlan: 99
    allowed_vlans: [10, 20, 100]
    members:
      - interface: GigabitEthernet1/1/3
        description: TRUNK_TO_S1-NCS540_Te0/0/0/26
        channel_group: 1
        channel_mode: active
      - interface: GigabitEthernet1/1/4
        description: TRUNK_TO_S1-NCS540_Te0/0/0/27
        channel_group: 1
        channel_mode: active

# No L3 SVIs on this switch - routing is on NCS540
svi_interfaces: []
